# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cfa851cce895f905895426b49630537d"
name = "qr-code-generator-definitive"
handle = "qr-code-generator-definitive"
application_url = "https://qr-code-generator-definitive.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_files,write_files"

[auth]
redirect_urls = [
  "https://qr-code-generator-definitive.vercel.app/auth/callback",
  "https://qr-code-generator-definitive.vercel.app/auth/shopify/callback",
  "https://qr-code-generator-definitive.vercel.app/api/auth/callback"
]

[pos]
embedded = false
